### ISSUE TITLE
VERIFY SHARE ON IOS

### ISSUE THREAD

**Issue by LatiniDav** [DavideTedesco/a-wonderful-platform-game#19]
Ricominciare o verificare esattezza tramite Android/IOS.

**Comment by DavideTedesco** [comment]
Functioning on Android to try on iOS

**Comment by DavideTedesco** [comment]
https://www.youtube.com/watch?v=DzH4UODL7Dc&ab_channel=GDi4K

**Comment by DavideTedesco** [comment]
functioning as expected similarly as Android!
