### ISSUE TITLE
TO IMPLEMENT JUMP

### ISSUE THREAD

**Issue by LatiniDav** [DavideTedesco/a-wonderful-platform-game#21]
Implementare comando salta per player in telefono

**Comment by DavideTedesco** [comment]
Partially implemented in [commit](https://github.com/DavideTedesco/a-wonderful-platform-game/commit/271f3c36d474a685395703967cc60c6612f0aa4f) not functioning yet!

**Comment by DavideTedesco** [comment]
Completed by @Skesky !
