### ISSUE TITLE
Suggested game names

### ISSUE THREAD

**Issue by DavideTedesco** [DavideTedesco/a-wonderful-platform-game#26]
- Run student run (@LatiniDav)
- Endless semesters
- 42
- Objective 180
- 30L

>Comment underneath with your preferred name!

**Comment by LatiniDav** [comment]
- Objective 110L
What do you think about?
@DavideTedesco @Skesky

**Comment by DavideTedesco** [comment]
Why not keeping the current mock name??? **Run Student Run** @LatiniDav @Skesky

**Comment by LatiniDav** [comment]
I'm agree

**Comment by DavideTedesco** [comment]
__Run Student Run__ is the name selected changes will be deployed with this name!
