### ISSUE TITLE
Decide how to do the passage from a level to another

### ISSUE THREAD

**Issue by DavideTedesco** [DavideTedesco/a-wonderful-platform-game#31]

**Comment by LatiniDav** [comment]
Proposal:
 1 - You play the level and when you get to a "flag / 18  image/ whatever you want" the game takes you back to the year corresponding to the level
 2 - You play the level and when you get to a "flag / 18  image/ whatever you want" the game takes you on the next level

Choose what you prefer or make a new proposal writing under this comment. Anyhow write something!

**Comment by LatiniDav** [comment]
Completed. I had no answer from you so I implemented all possibilities.

**Comment by DavideTedesco** [comment]
so you implemented both solutions @LatiniDav ?
