### ISSUE TITLE
IMPLEMENT Lv 2.x & Lv 3.x

### ISSUE THREAD

**Issue by LatiniDav** [DavideTedesco/a-wonderful-platform-game#40]
Implement lv 3.1, lv 3.2, lv 3.3, lv 3.4, lv 3.5

**Comment by LatiniDav** [comment]
Implement lv 2.1, lv 2.2, lv 2.3, lv 2.4, lv 2.5 too

**Comment by DavideTedesco** [comment]
all implemented
