### ISSUE TITLE
Problemi visualizzazione

### ISSUE THREAD

**Issue by LatiniDav** [DavideTedesco/a-wonderful-platform-game#5]
Se andate ad eseguire il codice troverete problematiche di visualizzazione del canvas delle varie page. Pensavo di aver capito che doveva essere di dimensioni 640x940 ma non viene visualizzato bene in questo modo.

**Comment by DavideTedesco** [comment]
Scaling to implement, a fixed resolution is not useful!

**Comment by LatiniDav** [comment]
Solved!
