### ISSUE TITLE
Custom splash screen

### ISSUE THREAD

**Issue by DavideTedesco** [DavideTedesco/a-wonderful-platform-game#56]

**Comment by DavideTedesco** [comment]
choose a representative image of the game for the splash screen

**Comment by DavideTedesco** [comment]
https://unity3d.college/2017/08/03/create-customize-your-unity3d-splash-screen-and-icons/

**Comment by LatiniDav** [comment]
Resolved

**Comment by LatiniDav** [comment]
Aborted idea
