### ISSUE TITLE
Movement sound definition and design

### ISSUE THREAD

**Issue by Skesky** [DavideTedesco/a-wonderful-platform-game#61]

**Comment by DavideTedesco** [comment]
Guides:
- https://blog.unity.com/technology/mod-in-unity
- https://docs.unity3d.com/Manual/TrackerModules.html

**Comment by DavideTedesco** [comment]
Added sounds and soundtrack in [commit](https://github.com/DavideTedesco/a-wonderful-platform-game/commit/d36fdc019cc91dd877facfca838f74554b517a51).

All the scripts has been done, the sounds must be dragged in all audio sources for handling and using them (e.g. for the books, hearts and player jumps!

**Comment by Skesky** [comment]
To be changed jump and double jump sound

**Comment by LatiniDav** [comment]
Resolved
