### ISSUE TITLE
Decide how a level should end

### ISSUE THREAD

**Issue by Skesky** [DavideTedesco/a-wonderful-platform-game#63]
https://assetstore.unity.com/packages/vfx/particles/environment/pixel-weather-particles-148577

**Comment by DavideTedesco** [comment]
Verbale drawn by @Skesky to be implemented!

**Comment by LatiniDav** [comment]
Verbale connected con winPanel to complete level. I only need to connect final grade with the book counter

**Comment by DavideTedesco** [comment]
The player catch the Verbale (of the Exam) and the Win Panel appear showing the number of books collected!
