### ISSUE TITLE
Many bugs beta5 release

### ISSUE THREAD

**Issue by LatiniDav** [DavideTedesco/a-wonderful-platform-game#73]
1. If you stay in authors page and you make a tap on back button you return on Login page and you can't return on the first page
2. Win Panel's buttons have no function. They are disconnect by a script
3. Level 2.1 create two player. You can play only with 1.x levels' player the other one is a "death player" with no movements.
4. In the end of 2.1 level there are three pink blocks  but they have no function and the player can go through them
5. in 1.1 the player starts the race from the end. This wasn't in previous releases

**Comment by DavideTedesco** [comment]
Answer to @LatiniDav on [beta5 release](https://github.com/DavideTedesco/a-wonderful-platform-game/releases/tag/beta5)
1. to be fixed
2. they have already been fixed and will be functionable in next release
3. the second subject is an enemy an will be present throughout the 2.x levels, levels 2.x and 3.x have to be implemented partialy
4. they are artifacts of the background and will be fixed
5. the player has been moved to the end to test the buttons on the win panel, the player will be moved to the initial position for the next release

**Comment by DavideTedesco** [comment]
Many bugs solved in [beta 6](https://github.com/DavideTedesco/a-wonderful-platform-game/releases/tag/beta6)
1. to be fixed
2. fixed
3. already explained
4. to be fixed
5. not fixed, for testing purposes
6. problems with buttons on the first year as mentioned [here](https://github.com/DavideTedesco/a-wonderful-platform-game/issues/76)

**Comment by LatiniDav** [comment]
Resolved

**Comment by LatiniDav** [comment]
Resolved

**Comment by LatiniDav** [comment]
Resolved
