### ISSUE TITLE
Can't access or play 1.x level

### ISSUE THREAD

**Issue by DavideTedesco** [DavideTedesco/a-wonderful-platform-game#76]
Can't access or play 1.x level

_Originally posted by @Skesky in https://github.com/DavideTedesco/a-wonderful-platform-game/pull/75#pullrequestreview-976736694_

**Comment by Skesky** [comment]
Issue solved on commit [](https://github.com/DavideTedesco/a-wonderful-platform-game/commit/d4b32e7e4830f2f805b881625065fac43b7c163a)

**Comment by Skesky** [comment]
Issue solved on commit [d4b32e7e](https://github.com/DavideTedesco/a-wonderful-platform-game/commit/d4b32e7e4830f2f805b881625065fac43b7c163a)
