### ISSUE TITLE
Add all sounds to all game objects level 1.x, 2.x and 3.x!

### ISSUE THREAD

**Issue by DavideTedesco** [DavideTedesco/a-wonderful-platform-game#88]
All game objects must implement the sounds added as described in [this issue](https://github.com/DavideTedesco/a-wonderful-platform-game/issues/61)!

To add sounds simply drag and drop audiosource files that are attached to the Main Camera object as described in the image below:
<img width="1680" alt="Screenshot 2022-06-03 at 10 11 59" src="https://user-images.githubusercontent.com/24352405/171823825-e7ca5da3-fb2c-4f57-8ada-0bfc3ca97323.png">

**Comment by DavideTedesco** [comment]
__IMPORTANT__ consider to upload your branch from Tedesco_Trash to implement all this stuff!

**Comment by LatiniDav** [comment]
Resolved
