### ISSUE TITLE
Decide if  we should implement OAuth 

### ISSUE THREAD

**Issue by Skesky** [DavideTedesco/a-wonderful-platform-game#92]
https://developer.okta.com/blog/2020/08/21/unity-csharp-games-security

**Comment by DavideTedesco** [comment]
If the implementation of OAuth will be done with Google, such implementation will be available only for Android devices! 
Similarly the implementation of OAuth with Apple will restrict the use to iOS devices only...

**Comment by LatiniDav** [comment]
Resolved

**Comment by LatiniDav** [comment]
Resolved
